// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lttlzgijgkxoqgyoovtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0dGx6Z2lqZ2t4b3FneW9vdnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjg1MDcsImV4cCI6MjA2OTY0NDUwN30.3I4fkZyQDfa3V62yYv__U7WziKPyrjPdQJhJDZzpgGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});